version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    command: /bin/bash -c 'npm run dev'
    volumes:
      - .:/workspace
      - node_modules_vol:/workspace/node_modules
    ports:
      - 9000:9000

volumes:
  # Exclude the node_modules directory
  # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
  node_modules_vol:
